<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UxwHRlXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.UxwHRlX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UxwHRlX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteThreeRepository' => ['privates', 'App\\Repository\\PosteThreeRepository', 'getPosteThreeRepositoryService', true],
        ], [
            'posteThreeRepository' => 'App\\Repository\\PosteThreeRepository',
        ]);
    }
}
