<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKPYkz2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZKPYkz2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZKPYkz2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteOne' => ['privates', '.errored..service_locator.ZKPYkz2.App\\Entity\\PosteOne', NULL, 'Cannot autowire service ".service_locator.ZKPYkz2": it needs an instance of "App\\Entity\\PosteOne" but this type has been excluded in "config/services.yaml".'],
        ], [
            'posteOne' => 'App\\Entity\\PosteOne',
        ]);
    }
}
