<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ASAIa0ZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ASAIa0Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ASAIa0Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteTwo' => ['privates', '.errored..service_locator.ASAIa0Z.App\\Entity\\PosteTwo', NULL, 'Cannot autowire service ".service_locator.ASAIa0Z": it needs an instance of "App\\Entity\\PosteTwo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'posteTwo' => 'App\\Entity\\PosteTwo',
        ]);
    }
}
