<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IuBNA6gService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.iuBNA6g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iuBNA6g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'posteTwo' => ['privates', '.errored..service_locator.iuBNA6g.App\\Entity\\PosteTwo', NULL, 'Cannot autowire service ".service_locator.iuBNA6g": it needs an instance of "App\\Entity\\PosteTwo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'posteTwo' => 'App\\Entity\\PosteTwo',
        ]);
    }
}
