<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FF5QxaMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.fF5QxaM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fF5QxaM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'posteOne' => ['privates', '.errored..service_locator.fF5QxaM.App\\Entity\\PosteOne', NULL, 'Cannot autowire service ".service_locator.fF5QxaM": it needs an instance of "App\\Entity\\PosteOne" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'posteOne' => 'App\\Entity\\PosteOne',
        ]);
    }
}
