<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteFourService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.gy4k0J..App\Entity\PosteFour' shared service.
     *
     * @return \App\Entity\PosteFour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gy4k0J.": it needs an instance of "App\\Entity\\PosteFour" but this type has been excluded in "config/services.yaml".');
    }
}
