<?php

namespace ContainerCF7Y3NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteTwo2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.iuBNA6g.App\Entity\PosteTwo' shared service.
     *
     * @return \App\Entity\PosteTwo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iuBNA6g": it needs an instance of "App\\Entity\\PosteTwo" but this type has been excluded in "config/services.yaml".');
    }
}
