<?php

namespace ContainerZCtie1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BdXnE7eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BdXnE7e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BdXnE7e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'giftRepository' => ['privates', 'App\\Repository\\GiftRepository', 'getGiftRepositoryService', true],
            'posteOneRepository' => ['privates', 'App\\Repository\\PosteOneRepository', 'getPosteOneRepositoryService', true],
        ], [
            'entityManager' => '?',
            'giftRepository' => 'App\\Repository\\GiftRepository',
            'posteOneRepository' => 'App\\Repository\\PosteOneRepository',
        ]);
    }
}
