<?php

namespace ContainerZCtie1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_07B3NrqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.07B3Nrq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.07B3Nrq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'medailleRepository' => ['privates', 'App\\Repository\\MedailleRepository', 'getMedailleRepositoryService', true],
        ], [
            'medailleRepository' => 'App\\Repository\\MedailleRepository',
        ]);
    }
}
