<?php

namespace ContainerZCtie1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGift2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ITjEuLJ.App\Entity\Gift' shared service.
     *
     * @return \App\Entity\Gift
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ITjEuLJ": it needs an instance of "App\\Entity\\Gift" but this type has been excluded in "config/services.yaml".');
    }
}
