<?php

namespace ContainerAOG91ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteThree2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.lKUROM5.App\Entity\PosteThree' shared service.
     *
     * @return \App\Entity\PosteThree
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lKUROM5": it needs an instance of "App\\Entity\\PosteThree" but this type has been excluded in "config/services.yaml".');
    }
}
