<?php

namespace ContainerAOG91ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteThreeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PosteThreeRepository' shared autowired service.
     *
     * @return \App\Repository\PosteThreeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PosteThreeRepository'] = new \App\Repository\PosteThreeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
