<?php

namespace ContainerOnrwGJM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGRMvjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P_gRMvj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P_gRMvj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'medaille' => ['privates', '.errored..service_locator.P_gRMvj.App\\Entity\\Medaille', NULL, 'Cannot autowire service ".service_locator.P_gRMvj": it needs an instance of "App\\Entity\\Medaille" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'medaille' => 'App\\Entity\\Medaille',
        ]);
    }
}
