<?php

namespace ContainerOnrwGJM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedailleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P_gRMvj.App\Entity\Medaille' shared service.
     *
     * @return \App\Entity\Medaille
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.P_gRMvj": it needs an instance of "App\\Entity\\Medaille" but this type has been excluded in "config/services.yaml".');
    }
}
