<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6hE3Lc9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6hE3Lc9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6hE3Lc9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteFourRepository' => ['privates', 'App\\Repository\\PosteFourRepository', 'getPosteFourRepositoryService', true],
        ], [
            'posteFourRepository' => 'App\\Repository\\PosteFourRepository',
        ]);
    }
}
