<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N1Oi9oLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N1Oi9oL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N1Oi9oL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteFour' => ['privates', 'App\\Repository\\PosteFourRepository', 'getPosteFourRepositoryService', true],
            'posteOne' => ['privates', 'App\\Repository\\PosteOneRepository', 'getPosteOneRepositoryService', true],
            'posteThree' => ['privates', 'App\\Repository\\PosteThreeRepository', 'getPosteThreeRepositoryService', true],
            'posteTwo' => ['privates', 'App\\Repository\\PosteTwoRepository', 'getPosteTwoRepositoryService', true],
        ], [
            'posteFour' => 'App\\Repository\\PosteFourRepository',
            'posteOne' => 'App\\Repository\\PosteOneRepository',
            'posteThree' => 'App\\Repository\\PosteThreeRepository',
            'posteTwo' => 'App\\Repository\\PosteTwoRepository',
        ]);
    }
}
