<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PliRqEpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PliRqEp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PliRqEp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteThree' => ['privates', '.errored..service_locator.PliRqEp.App\\Entity\\PosteThree', NULL, 'Cannot autowire service ".service_locator.PliRqEp": it needs an instance of "App\\Entity\\PosteThree" but this type has been excluded in "config/services.yaml".'],
        ], [
            'posteThree' => 'App\\Entity\\PosteThree',
        ]);
    }
}
