<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QopCnShService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QopCnSh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QopCnSh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteOneRepository' => ['privates', 'App\\Repository\\PosteOneRepository', 'getPosteOneRepositoryService', true],
        ], [
            'posteOneRepository' => 'App\\Repository\\PosteOneRepository',
        ]);
    }
}
