<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultiResaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MultiResaController' shared autowired service.
     *
     * @return \App\Controller\MultiResaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MultiResaController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PricingService.php';

        $container->services['App\\Controller\\MultiResaController'] = $instance = new \App\Controller\MultiResaController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PosteOneRepository'] ?? $container->load('getPosteOneRepositoryService')), ($container->privates['App\\Repository\\PosteTwoRepository'] ?? $container->load('getPosteTwoRepositoryService')), ($container->privates['App\\Repository\\PosteThreeRepository'] ?? $container->load('getPosteThreeRepositoryService')), ($container->privates['App\\Repository\\PosteFourRepository'] ?? $container->load('getPosteFourRepositoryService')), ($container->privates['App\\Service\\PricingService'] ??= new \App\Service\PricingService()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\MultiResaController', $container));

        return $instance;
    }
}
