<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteTwoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ASAIa0Z.App\Entity\PosteTwo' shared service.
     *
     * @return \App\Entity\PosteTwo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ASAIa0Z": it needs an instance of "App\\Entity\\PosteTwo" but this type has been excluded in "config/services.yaml".');
    }
}
