<?php

namespace ContainerF6gqX7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteTwoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PosteTwoController' shared autowired service.
     *
     * @return \App\Controller\PosteTwoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PosteTwoController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PricingService.php';

        $container->services['App\\Controller\\PosteTwoController'] = $instance = new \App\Controller\PosteTwoController(($container->privates['App\\Service\\PricingService'] ??= new \App\Service\PricingService()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PosteTwoController', $container));

        return $instance;
    }
}
